Repository kuldeep700/Form-page, pull requests merged in 2025-10, with the labels that each got.

#2 fix: updated form styling to match design
  Second_Program/employee_form.html
  Second_Program/faculty_form.html
  Second_Program/index.html
  Second_Program/student_form.html
  Second_Program/style.css
Labels: good first issue, hacktoberfest-accepted

#4 add readme
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#6 UI: Modernize portal — hero, cards, floating forms & client-side toast
  Second_Program/employee_form.html
  Second_Program/faculty_form.html
  Second_Program/index.html
  Second_Program/script.js
  Second_Program/student_form.html
  Second_Program/style.css
Labels: hacktoberfest, hacktoberfest-accepted
